name: Update gist with WakaTime stats
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 036c73be98c0dd6bf59dbe9d623a6b33
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
